Nothing:
Proxy data@Text: #{data}
Yes: Yes
No: No
Active: Active
AlreadyExists: Already exists
Edit: Edit
Balance: Balance
CurrencyCode: Currency
CurrencyCodeSelect: Select the desired currency
WeekDay: Week day
StartsAt: From
EndsAt: To
Time: Time
NamePerson: Name
NameObject: Name
Qty: Quantity
Primary: Primary
Secondary: Secondary
Availability: Availability
InOrganization: Organization working hours
Anytime: Anytime
Kind: Kind
FirstName: First name
LastName: Last name
Location: Location
Date: Date
BasePrice currency@Rentier.Currency.Code: Base Price (#{show currency})
BaseRentDuration: Base rent duration
MinimalRentDuration: Minimal rent duration
DefaultMinimalRentDuration: Default minimal rent duration
IframeTimeResolution: Widget time resolution
DefaultIframeTimeResolution: Default widget time resolution
PosNumIsRequired: Positive number is required
NaturalNumIsRequired: Natural number is required
Schedule: Schedule
GeneralInfo: General info
Property: Service
PropertyPrimary: Main service
PropertySecondary: Additional service
EmployeeIdent: Phone number
Continue: Continue
Pcs qty@Int: x #{show qty}

Sunday: Sunday
Monday: Monday
Tuesday: Tuesday
Wednesday: Wednesday
Thursday: Thursday
Friday: Friday
Saturday: Saturday

ShortSunday: Sun
ShortMonday: Mon
ShortTuesday: Tue
ShortWednesday: Wed
ShortThursday: Thu
ShortFriday: Fri
ShortSaturday: Sat

HomeRBreadcrumb: Home
AuthRBreadcrumb: Login
SignoutRBreadcrumb: Signout
ProfileRBreadcrumb: Profile
MerchantCreateRBreadcrumb: Profile
OrganizationListRBreadcrumb: Organizations
CreateRBreadcrumb: New
OrganizationScheduleCreateRBreadcrumb: New schedule rule
OrganizationScheduleUpdateRBreadcrumb: Edit schedule rule
OrganizationScheduleDeleteRBreadcrumb: Delete schedule rule
PropertyCreateRBreadcrumb: New property
EmployeeListRBreadcrumb: Employees
IframePropertyScheduleRBreadcrumb: Schedule
IframeSessionCreateRBreadcrumb: Reservation
IframeSessionConfirmRBreadcrumb: Confirm

HomeRTitle: Welcome | Rentier
SignoutRTitle: Logout | Rentier
ProfileRTitle ident@Text: #{ident} | Rentier
MerchantCreateRTitle ident@Text: #{ident} | Rentier
OrganizationListRTitle ident@Text: Organizations | #{ident} | Rentier
OrganizationCreateRTitle ident@Text: New organization | #{ident} | Rentier
OrganizationUpdateRTitle ident@Text: #{ident} | Rentier
OrganizationScheduleCreateRTitle ident@Text: New schedule rule | #{ident} | Rentier
OrganizationScheduleUpdateRTitle ident@Text: Edit schedule rule | #{ident} | Rentier
OrganizationScheduleDeleteRTitle ident@Text: Delete schedule rule | #{ident} | Rentier
PropertyCreateRTitle ident@Text: New property | #{ident} | Rentier
PropertyUpdateRTitle ident@Text: #{ident} | Rentier
EmployeeListRTitle ident@Text: Employees | #{ident} | Rentier
EmployeeCreateRTitle ident@Text: New employee | #{ident} | Rentier

LoginAsMerchant: Login as merchant
LoginAsEmployee: Login as employee

Home: Home
Profile: Profile
Organizations: Organizations
Employees: Employees
Login: Login
Logout: Logout
ForMerchant: Merchant's
ForEmployee: Employee's
Iso639v1: en
Iso3166v1: ee

HomeBigHeader: Modern solution for online reservations
HomeSmallHeader: One system. All platforms. For free.

ProfilePageGreetAnon ident@Text: You are logged in, #{ident}
ProfilePageGreetMerchant ident@Text: You are logged in as merchant, #{ident}
ProfilePageGreetEmployee ident@Text: You are logged in as employee, #{ident}
ProfilePageGreetCustomer ident@Text: You are logged in as customer, #{ident}
ProfilePageUpdate: Update my profile
ProfilePageUpdated: Profile has been updated

MyOrganizations: My organizations
MyEmployees: My employees

MerchantCreate: Register as a merchant
MerchantCreated: Your business account is created

OrganizationEmpty: Currently you have no organizations
OrganizationCreate: Create organization
OrganizationUpdate: Update organization

OrganizationName: Name
OrganizationCreated organizationName@Text: Organization "#{organizationName}" created
OrganizationUpdated organizationName@Text: Organization "#{organizationName}" updated

OrganizationScheduleEmpty: Currently you don't have schedule rules for this organization
OrganizationScheduleCreate: Add organization schedule rule
OrganizationScheduleCreated: Organization schedule has been created
OrganizationScheduleUpdate: Update organization schedule rule
OrganizationScheduleUpdated: Organization schedule has been updated
OrganizationScheduleDelete: Delete organization schedule rule
OrganizationScheduleDeleted: Organization schedule has been removed

PropertyEmpty: Currently you don't have any property for this organization
PropertyCreate: Add organization property
PropertyCreated: Organization property has been created
PropertyUpdate: Update organization property
PropertyUpdated: Organization property has been updated

EmployeeEmpty: Currently you don't have any employees
EmployeeCreate: Add employees
EmployeeCreated: Employee has been added

TimeKind: Schedule rule type
WorkingTime: Working time
BreakTime: Break time

EmployeeInvitationStatus: Invitation status
EmployeeInvitationStatusPending: Pending
EmployeeInvitationStatusAccepted: Accepted
EmployeeInvitationStatusDeclined: Declined

Comment: Comment
CustomerComment: Customer comment
EmployeeComment: Employee comment
