Nothing:
Proxy data@Text: #{data}
Yes: Да
No: Нет
Active: Активно
AlreadyExists: Уже существует
Edit: Редактировать
Balance: Баланс
CurrencyCode: Валюта
CurrencyCodeSelect: Выберите желаемую валюту
WeekDay: День недели
StartsAt: С
EndsAt: До
Time: Время
NamePerson: Имя
NameObject: Название
Qty: Количество
Primary: Основной
Secondary: Дополнительный
Availability: Доступность
InOrganization: Часы работы фирмы
Anytime: Любое время
Kind: Тип
FirstName: Имя
LastName: Фамилия
Location: Место
Date: Дата
BasePrice currency@Rentier.Currency.Code: Базовая цена (#{show currency})
BaseRentDuration: Базовая продолжительность аренды
MinimalRentDuration: Минимальная продолжительность аренды
DefaultMinimalRentDuration: Минимальная продолжительность аренды по умолчанию
IframeTimeResolution: Минимально различимое время на виджете
DefaultIframeTimeResolution: Минимально различимое время на виджете по умолчанию
PosNumIsRequired: Требуется число больше 0
NaturalNumIsRequired: Требуется число от 1 и больше
Schedule: Режим работы
GeneralInfo: Основная информация
Property: Услуга
PropertyPrimary: Главная услуга
PropertySecondary: Дополнительная услуга
EmployeeIdent: Номер телефона
Continue: Продолжить
Pcs qty@Int: x #{show qty}

Sunday: Воскресенье
Monday: Понедельник
Tuesday: Вторник
Wednesday: Среда
Thursday: Четверг
Friday: Пятница
Saturday: Суббота

ShortSunday: ВС
ShortMonday: ПН
ShortTuesday: ВТ
ShortWednesday: СР
ShortThursday: ЧТ
ShortFriday: ПТ
ShortSaturday: СБ

HomeRBreadcrumb: Главная
AuthRBreadcrumb: Войти
SignoutRBreadcrumb: Выйти
ProfileRBreadcrumb: Профиль
MerchantCreateRBreadcrumb: Профиль
OrganizationListRBreadcrumb: Организации
CreateRBreadcrumb: Создать
OrganizationScheduleCreateRBreadcrumb: Задать правило расписания
OrganizationScheduleUpdateRBreadcrumb: Изменить правило расписания
OrganizationScheduleDeleteRBreadcrumb: Удалить правило расписания
PropertyCreateRBreadcrumb: Новая собственность
EmployeeListRBreadcrumb: Работники
IframePropertyScheduleRBreadcrumb: Расписание
IframeSessionCreateRBreadcrumb: Бронь
IframeSessionConfirmRBreadcrumb: Подтвердить

HomeRTitle: Добро пожаловать | Rentier
SignoutRTitle: Выйти | Rentier
ProfileRTitle x@User: #{x} | Rentier
MerchantCreateRTitle x@User: #{x} | Rentier
OrganizationListRTitle x@User: Организации | #{x} | Rentier
OrganizationCreateRTitle x@User: Новая организация | #{x} | Rentier
OrganizationUpdateRTitle ident@Text: #{ident} | Rentier
OrganizationScheduleCreateRTitle ident@Text: Задать правило расписания | #{ident} | Rentier
OrganizationScheduleUpdateRTitle ident@Text: Изменить правило расписания | #{ident} | Rentier
OrganizationScheduleDeleteRTitle ident@Text: Удалить правило расписания | #{ident} | Rentier
PropertyCreateRTitle ident@Text: Новая собственность | #{ident} | Rentier
PropertyUpdateRTitle ident@Text: #{ident} | Rentier
EmployeeListRTitle x@User: Работники | #{x} | Rentier
EmployeeCreateRTitle x@User: Новый работник | #{x} | Rentier

LoginAsMerchant: Войти как предприниматель
LoginAsEmployee: Войти как работник

Home: Главная
Profile: Профиль
Organizations: Организации
Employees: Работники
Login: Войти
Logout: Выйти
ForMerchant: Бизнесу
ForEmployee: Работнику
Iso639v1: ru
Iso3166v1: ru

HomeBigHeader: Современное решение для онлайн бронирования
HomeSmallHeader: Одна система. Все платформы. Бесплатно.

ProfilePageGreetAnon x@User: Вы вошли как #{x}
ProfilePageGreetMerchant x@User: Вы вошли как предприниматель, #{x}
ProfilePageGreetEmployee x@User: Вы вошли как работник, #{x}
ProfilePageGreetCustomer x@User: Вы вошли как клиент, #{x}
ProfilePageUpdate: Обновить мой профиль
ProfilePageUpdated: Профиль был обновлён

MyOrganizations: Мои организации
MyEmployees: Мои работники

MerchantCreate: Войти как бизнес
MerchantCreated: Ваш бизнес аккаунт создан

OrganizationEmpty: В настоящее время у вас нет организаций
OrganizationCreate: Создать организацию
OrganizationUpdate: Обновить организацию

OrganizationName: Название
OrganizationCreated organizationName@Text: Организация "#{organizationName}" создана
OrganizationUpdated organizationName@Text: Организация "#{organizationName}" обновлена

OrganizationScheduleEmpty: В настоящее время для данной организации правила режима работы не установлены
OrganizationScheduleCreate: Добавить правило режима работы
OrganizationScheduleCreated: Режим работы организации был обновлён
OrganizationScheduleUpdate: Обновить правило режима работы
OrganizationScheduleUpdated: Режим работы организации был обновлён
OrganizationScheduleDelete: Удалить правило режима работы
OrganizationScheduleDeleted: Правило режима работы было удалено

PropertyEmpty: В настоящее время для данной организации не добавлена собственность
PropertyCreate: Добавить собственность
PropertyCreated: Собственность была добавлена
PropertyUpdate: Обновить собственность
PropertyUpdated: Собственность была обновлена

EmployeeEmpty: В настоящее время ваши работники не добавлены
EmployeeCreate: Добавить работника
EmployeeCreated: Работник был добавлен

TimeKind: Тип режима работы
WorkingTime: Рабочее время
BreakTime: Перерыв

EmployeeInvitationStatus: Статус приглашения
EmployeeInvitationStatusPending: Отправлено
EmployeeInvitationStatusAccepted: Принято
EmployeeInvitationStatusDeclined: Отклонено

Comment: Комментарий
CustomerComment: Комментарий клиента
EmployeeComment: Комментарий работника
